<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7bwfncm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7bwfncm/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7bwfncm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7bwfncm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7bwfncm\appProdProjectContainer([
    'container.build_hash' => '7bwfncm',
    'container.build_id' => '606582fe',
    'container.build_time' => 1672362486,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7bwfncm');
